from settings import *

player_texture_data = {
    'player_idle_down':{    
        'type':'player',
        'size':(PLAYER_SPRITESIZE,PLAYER_SPRITESIZE), 
        'position':(0,0),
        'frames':6,
        'file_path':'Assets/Character/Proto_Idle_Down.png'
        },
    'player_walk_down':{    
        'type':'player',
        'size':(PLAYER_SPRITESIZE,PLAYER_SPRITESIZE), 
        'position':(0,0),
        'frames':6,
        'file_path':'Assets/Character/Proto_Walk_Down.png'
        },
    'player_idle_up':{    
        'type':'player',
        'size':(PLAYER_SPRITESIZE,PLAYER_SPRITESIZE), 
        'position':(0,0),
        'frames':6,
        'file_path':'Assets/Character/Proto_Idle_Up.png'
        },
    'player_walk_up':{    
        'type':'player',
        'size':(PLAYER_SPRITESIZE,PLAYER_SPRITESIZE), 
        'position':(0,0),
        'frames':6,
        'file_path':'Assets/Character/Proto_Walk_Up.png'
        },
    'player_idle_right':{    
        'type':'player',
        'size':(PLAYER_SPRITESIZE,PLAYER_SPRITESIZE), 
        'position':(0,0),
        'frames':6,
        'file_path':'Assets/Character/Proto_Idle_Right.png'
        },
    'player_walk_right':{    
        'type':'player',
        'size':(PLAYER_SPRITESIZE,PLAYER_SPRITESIZE), 
        'position':(0,0),
        'frames':6,
        'file_path':'Assets/Character/Proto_Walk_Right.png'
        },     
    'player_idle_left':{    
        'type':'player',
        'size':(PLAYER_SPRITESIZE,PLAYER_SPRITESIZE), 
        'position':(0,0),
        'frames':6,
        'file_path':'Assets/Character/Proto_Idle_Right.png'
        },
    'player_walk_left':{    
        'type':'player',
        'size':(PLAYER_SPRITESIZE,PLAYER_SPRITESIZE), 
        'position':(0,0),
        'frames':6,
        'file_path':'Assets/Character/Proto_Walk_Right.png'
        },    
}
