#!/bin/sh

return_error() {
    echo "Error: $1. Fix before pushing."
    exit 1
}

python -m black . || return_error "Code formatting failed."

FILES=$(git diff --name-only --cached | grep '\.py$')

if [ -n "$FILES" ]; then
    python -m pylint --errors-only $FILES || return_error "Pylint found errors."
else
    echo "No Python files changed, skipping Pylint."
fi

python line_counter.py || return_error "Counting lines failed"

if [ -f "README.md" ]; then
    git add README.md
    echo "README.md stats updated and staged."
fi

exit 0