#!/bin/sh

return_error() {
    echo "❌ Error: $1. Fix before committing."
    exit 1
}

echo "--- Running Pre-Commit Hooks ---"

python -m black . || return_error "Black formatting failed"
git add . 

# FILES=$(git diff --name-only --cached | grep '\.py$')

# if [ -n "$FILES" ]; then
#     echo "Checking for Pylint errors..."
#     python -m pylint --errors-only $FILES || return_error "Pylint found errors."
# else
#     echo "No Python files staged; skipping Pylint."
# fi

if [ -f "line_counter.py" ]; then
    python line_counter.py || return_error "Line counting script failed"
else
    return_error "line_counter.py not found"
fi

if [ -f "README.md" ]; then
    git add README.md
    echo "✅ README.md updated and included in this commit."
fi

exit 0