#!/bin/sh

return_error() {
    echo "Error: $1. Fix before pushing."
    exit 1
}

python -m black . || return_error "Code formatting failed."

python -m pylint --errors-only . || return_error "Pylint checks failed."

python line_counter.py || return_error "Counting lines failed"

if [ -f "README.md" ]; then
    git add README.md
    echo "README.md stats updated and staged."
fi

exit 0